"""SortSmart knowledge base: household items mapped to waste streams.

Categories: recycle, compost, ewaste, hazardous, landfill, donate, reuse.
Each entry: keywords (matched against user input), category, why, tip.
"""

ITEMS = [
    # ---- RECYCLABLES ----
    {"keywords": ["plastic bottle", "water bottle", "soda bottle", "pet bottle"],
     "category": "recycle", "why": "PET (#1) bottles are widely recyclable. Empty, rinse, and keep the cap on.",
     "tip": "Crush the bottle to save bin space."},
    {"keywords": ["milk jug", "detergent bottle", "hdpe"],
     "category": "recycle", "why": "HDPE (#2) jugs and bottles are accepted by most curbside programs.",
     "tip": "Rinse out residue — one dirty jug can contaminate a whole batch."},
    {"keywords": ["cardboard box", "shipping box", "corrugated"],
     "category": "recycle", "why": "Corrugated cardboard is highly recyclable when clean and dry.",
     "tip": "Flatten boxes. Tape is fine to leave on."},
    {"keywords": ["newspaper", "magazine", "junk mail", "office paper", "envelope"],
     "category": "recycle", "why": "Clean paper fiber can be recycled 5-7 times before fibers get too short.",
     "tip": "Shredded paper goes in too, but bag it so it doesn't blow away."},
    {"keywords": ["aluminum can", "soda can", "beer can", "tin can", "steel can", "food can"],
     "category": "recycle", "why": "Metal recycles forever without quality loss — an aluminum can becomes a new can in ~60 days.",
     "tip": "Rinse cans. Labels can stay on."},
    {"keywords": ["glass bottle", "glass jar", "wine bottle", "jam jar"],
     "category": "recycle", "why": "Glass is infinitely recyclable. Keep colors mixed only if your program allows.",
     "tip": "Rinse, no need to remove labels. Never put broken glass loose — wrap it."},
    {"keywords": ["pizza box"],
     "category": "compost", "why": "Grease-soaked cardboard can't be recycled — grease ruins paper recycling. But it composts fine.",
     "tip": "Tear off the clean lid for recycling, compost the greasy bottom."},
    {"keywords": ["egg carton", "paper egg carton"],
     "category": "compost", "why": "Paper egg cartons compost well; plastic/foam ones go to landfill.",
     "tip": "Paper carton → compost. Plastic or foam carton → landfill."},
    # ---- COMPOST ----
    {"keywords": ["banana peel", "apple core", "fruit scraps", "vegetable scraps", "food scraps", "coffee grounds", "tea bag", "eggshell"],
     "category": "compost", "why": "Food scraps in landfill rot without oxygen and release methane — a greenhouse gas 80x more potent than CO2 short-term.",
     "tip": "Keep a countertop caddy; empty it every 2-3 days to avoid smells."},
    {"keywords": ["yard waste", "leaves", "grass clippings", "branches", "twigs"],
     "category": "compost", "why": "Yard waste is ~20% of landfill volume in many cities. Composting returns it to soil.",
     "tip": "Leave grass clippings on the lawn — free fertilizer."},
    {"keywords": ["paper towel", "napkin", "paper napkin"],
     "category": "compost", "why": "Soiled paper can't be recycled (fibers too short and dirty) but composts fine.",
     "tip": "Only compost napkins without cleaning chemicals on them."},
    {"keywords": ["wooden toothpick", "popsicle stick", "wooden skewer"],
     "category": "compost", "why": "Untreated wood breaks down in compost.",
     "tip": "Snap into small pieces to speed it up."},
    # ---- E-WASTE ----
    {"keywords": ["phone", "smartphone", "old phone", "mobile"],
     "category": "ewaste", "why": "Phones contain lead, mercury, and cadmium — plus recoverable gold, copper, and rare earths.",
     "tip": "Wipe your data first. Many manufacturers take old phones back free."},
    {"keywords": ["laptop", "old laptop", "notebook computer"],
     "category": "ewaste", "why": "Laptops hold batteries and circuit boards that leach toxins in landfill.",
     "tip": "Remove the hard drive if you want to keep or destroy it separately."},
    {"keywords": ["battery", "aa battery", "aaa battery", "lithium battery", "rechargeable battery"],
     "category": "ewaste", "why": "Batteries cause landfill fires and leak heavy metals. They need dedicated e-waste collection.",
     "tip": "Tape the terminals of lithium batteries before drop-off — fire risk."},
    {"keywords": ["charger", "cable", "usb cable", "power cord", "earbuds", "headphones"],
     "category": "ewaste", "why": "Cables and small electronics contain copper and plastics worth recovering.",
     "tip": "Keep a small e-waste box at home; drop it off when full."},
    {"keywords": ["tv", "television", "monitor", "old monitor"],
     "category": "ewaste", "why": "Screens contain lead (CRT) or mercury (older LCD backlights). Never landfill.",
     "tip": "Retailers often accept old TVs when you buy a new one."},
    {"keywords": ["light bulb", "cfl", "fluorescent tube", "led bulb"],
     "category": "ewaste", "why": "CFLs and fluorescents contain mercury vapor. LEDs are e-waste too.",
     "tip": "Old-style incandescent bulbs (no mercury) → landfill, wrapped."},
    {"keywords": ["printer", "ink cartridge", "toner"],
     "category": "ewaste", "why": "Printers are e-waste; cartridges are often refillable or take-back eligible.",
     "tip": "Ask the manufacturer about free cartridge mail-back programs."},
    # ---- HAZARDOUS ----
    {"keywords": ["paint", "paint can", "spray paint"],
     "category": "hazardous", "why": "Paint contains solvents and heavy metals that contaminate soil and water.",
     "tip": "Take to a household hazardous waste event. Dried latex paint cans (lid off) are landfill-safe in many areas."},
    {"keywords": ["motor oil", "used oil", "cooking oil"],
     "category": "hazardous", "why": "One litre of oil can contaminate a million litres of water.",
     "tip": "Auto shops accept used motor oil free. Cooking oil: seal in a bottle, never pour down the drain."},
    {"keywords": ["pesticide", "herbicide", "weed killer", "rat poison"],
     "category": "hazardous", "why": "These are designed to kill — they don't belong in trash or drains.",
     "tip": "Keep in original containers for the hazardous waste drop-off."},
    {"keywords": ["bleach", "cleaning chemical", "drain cleaner", "ammonia"],
     "category": "hazardous", "why": "Corrosive chemicals endanger sanitation workers and water systems.",
     "tip": "Use them up, give away, or take to hazardous waste collection."},
    {"keywords": ["thermometer", "mercury thermometer"],
     "category": "hazardous", "why": "A single mercury thermometer holds enough mercury to pollute a small lake.",
     "tip": "Handle carefully, double-bag, take to hazardous waste."},
    # ---- DONATE / REUSE ----
    {"keywords": ["clothes", "shirt", "pants", "jacket", "shoes", "old clothes"],
     "category": "donate", "why": "Textiles take 200+ years to decompose and release methane. Wearable clothes get a second life.",
     "tip": "Even worn-out textiles can go to textile recyclers — don't trash them."},
    {"keywords": ["book", "old books", "textbook"],
     "category": "donate", "why": "Books are hard to recycle (glue bindings) but easy to rehome.",
     "tip": "Libraries, schools, and little free libraries take them."},
    {"keywords": ["furniture", "chair", "table", "couch", "sofa", "mattress"],
     "category": "donate", "why": "Bulky furniture fills landfills fast; most of it is still usable.",
     "tip": "Charities often pick up furniture free. Mattresses: check for a recycling program first."},
    {"keywords": ["toy", "old toys", "stuffed animal"],
     "category": "donate", "why": "Kids outgrow toys long before the toys wear out.",
     "tip": "Clean them first — shelters appreciate ready-to-give items."},
    {"keywords": ["plastic bag", "grocery bag", "shopping bag"],
     "category": "reuse", "why": "Plastic bags jam recycling machinery — never put them in curbside recycling.",
     "tip": "Return them to grocery store collection bins, or reuse as trash liners."},
    {"keywords": ["bubble wrap", "packing peanuts", "packing material"],
     "category": "reuse", "why": "Reuse beats recycling for packaging — it's already manufactured.",
     "tip": "Shipping stores often accept clean packing material."},
    {"keywords": ["jar", "mason jar"],
     "category": "reuse", "why": "Glass jars are endlessly reusable for storage before they ever need recycling.",
     "tip": "Pantry storage, leftovers, bulk shopping — jars replace disposables."},
    # ---- LANDFILL (last resort) ----
    {"keywords": ["chip bag", "crisp packet", "candy wrapper", "plastic wrapper", "sachet"],
     "category": "landfill", "why": "Multi-layer films (plastic + foil) can't be separated economically — no recycling stream takes them.",
     "tip": "Buy in bulk or choose paper packaging to avoid these entirely."},
    {"keywords": ["styrofoam", "foam cup", "foam container", "polystyrene"],
     "category": "landfill", "why": "Foam is 95% air — recyclers lose money on it, so almost none accept it.",
     "tip": "Refuse foam where you can; bring your own cup."},
    {"keywords": ["diaper", "sanitary pad", "wet wipe", "baby wipe"],
     "category": "landfill", "why": "Hygiene products are contaminated and multi-material — landfill only. Never flush wipes.",
     "tip": "'Flushable' wipes aren't — they clog sewers. Bin them."},
    {"keywords": ["broken ceramic", "broken plate", "mirror", "window glass", "pyrex"],
     "category": "landfill", "why": "Ceramics and treated glass melt at different temperatures than container glass — recyclers reject them.",
     "tip": "Wrap sharp pieces in newspaper and label the bag."},
    {"keywords": ["cigarette", "cigarette butt"],
     "category": "landfill", "why": "Butts are cellulose acetate plastic full of toxins — the #1 littered item worldwide.",
     "tip": "Pocket ashtrays exist. Best tip: quit."},
    {"keywords": ["toothbrush", "razor", "disposable razor"],
     "category": "landfill", "why": "Multi-material personal items have no recycling stream in most cities.",
     "tip": "Switch to bamboo toothbrushes (compostable handle)."},
    {"keywords": ["receipt", "thermal receipt"],
     "category": "landfill", "why": "Thermal paper is coated with BPA/BPS — it contaminates paper recycling.",
     "tip": "Ask for email receipts instead."},
]

CATEGORY_INFO = {
    "recycle": {"label": "Recycle", "emoji": "♻️", "diverts": True},
    "compost": {"label": "Compost", "emoji": "🌱", "diverts": True},
    "ewaste": {"label": "E-waste drop-off", "emoji": "🔋", "diverts": True},
    "hazardous": {"label": "Hazardous waste collection", "emoji": "☠️", "diverts": True},
    "donate": {"label": "Donate", "emoji": "🤲", "diverts": True},
    "reuse": {"label": "Reuse", "emoji": "🔁", "diverts": True},
    "landfill": {"label": "Landfill (last resort)", "emoji": "🗑️", "diverts": False},
}
